apiVersion: v1
data:  
  APP_PROTOCOLO: "${APP_PROTOCOLO}"
  APP_HOST: "${APP_HOST}"
  APP_ORGAO: "${APP_ORGAO}"
  APP_ORGAO_DESCRICAO: "${APP_ORGAO_DESCRICAO}"
  APP_NOMECOMPLEMENTO: "${APP_NOMECOMPLEMENTO}"
  APP_MEMCACHED_HOST: "${APP_MEMCACHED_HOST}"
  APP_DB_TIPO: "${APP_DB_TIPO}"
  APP_DB_HOST: "${APP_DB_HOST}"
  APP_SOLR_URL: "${APP_SOLR_URL}"
  APP_SOLR_CORE_PROTOCOLOS: "${APP_SOLR_CORE_PROTOCOLOS}"
  APP_SOLR_TEMPO_COMMIT_PROTOCOLOS: "${APP_SOLR_TEMPO_COMMIT_PROTOCOLOS}"
  APP_SOLR_CORE_BASECONHECIMENTO: "${APP_SOLR_CORE_BASECONHECIMENTO}"
  APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO: "${APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO}"
  APP_SOLR_CORE_PUBLICACOES: "${APP_SOLR_CORE_PUBLICACOES}"
  APP_SOLR_TEMPO_COMMIT_PUBLICACOES: "${APP_SOLR_TEMPO_COMMIT_PUBLICACOES}"
  APP_MAIL_TIPO: "${APP_MAIL_TIPO}"
  APP_MAIL_SERVIDOR: "${APP_MAIL_SERVIDOR}"
  APP_MAIL_CODIFICACAO: "${APP_MAIL_CODIFICACAO}"
  APP_MAIL_MAXDESTINATARIOS: "${APP_MAIL_MAXDESTINATARIOS}"
  APP_MAIL_MAXTAMANHOANEXOSMB: "${APP_MAIL_MAXTAMANHOANEXOSMB}"
  APP_MAIL_PROTEGIDO: "${APP_MAIL_PROTEGIDO}"
  APP_FONTES_GIT_PATH: "${APP_FONTES_GIT_PATH}"
  APP_FONTES_GIT_CHECKOUT: "${APP_FONTES_GIT_CHECKOUT}"
  OPENLDAP_PRESENTE: "${OPENLDAP_PRESENTE}"
  OPENLDAP_ADMIN_PASSWORD: "${OPENLDAP_ADMIN_PASSWORD}"
  OPENLDAP_DESLIGAR_NO_ORGAO_0: "${OPENLDAP_DESLIGAR_NO_ORGAO_0}"
  SERVICO_PD_INSTALAR: "${SERVICO_PD_INSTALAR}"
  SERVICO_PD_SIGLA: "${SERVICO_PD_SIGLA}"
  SERVICO_PD_NOME: "${SERVICO_PD_NOME}"
  SERVICO_PD_OPERACOES: "${SERVICO_PD_OPERACOES}"
  MODULO_ESTATISTICAS_INSTALAR: "${MODULO_ESTATISTICAS_INSTALAR}"
  MODULO_ESTATISTICAS_VERSAO: "${MODULO_ESTATISTICAS_VERSAO}"
  MODULO_ESTATISTICAS_URL: "${MODULO_ESTATISTICAS_URL}"
  MODULO_ESTATISTICAS_SIGLA: "${MODULO_ESTATISTICAS_SIGLA}"
  MODULO_ESTATISTICAS_CHAVE: "${MODULO_ESTATISTICAS_CHAVE}"
  MODULO_REST_INSTALAR: "${MODULO_REST_INSTALAR}"
  MODULO_REST_VERSAO: "${MODULO_REST_VERSAO}"
  MODULO_REST_URL_NOTIFICACAO: "${MODULO_REST_URL_NOTIFICACAO}"
  MODULO_REST_ID_APP: "${MODULO_REST_ID_APP}"
  MODULO_REST_CHAVE: "${MODULO_REST_CHAVE}"
  MODULO_REST_TOKEN_SECRET: "${MODULO_REST_TOKEN_SECRET}"
  MODULO_RESPOSTA_INSTALAR: "${MODULO_RESPOSTA_INSTALAR}"
  MODULO_RESPOSTA_VERSAO: "${MODULO_RESPOSTA_VERSAO}"
  MODULO_RESPOSTA_SISTEMA_ID: "${MODULO_RESPOSTA_SISTEMA_ID}"
  MODULO_RESPOSTA_DOCUMENTO_ID: "${MODULO_RESPOSTA_DOCUMENTO_ID}"
  MODULO_GESTAODOCUMENTAL_INSTALAR: "${MODULO_GESTAODOCUMENTAL_INSTALAR}"
  MODULO_GESTAODOCUMENTAL_VERSAO: "${MODULO_GESTAODOCUMENTAL_VERSAO}"
  MODULO_LOGINUNICO_INSTALAR: "${MODULO_LOGINUNICO_INSTALAR}"
  MODULO_LOGINUNICO_VERSAO: "${MODULO_LOGINUNICO_VERSAO}"
  MODULO_LOGINUNICO_CLIENTID: "${MODULO_LOGINUNICO_CLIENTID}"
  MODULO_LOGINUNICO_SECRET: "${MODULO_LOGINUNICO_SECRET}"
  MODULO_LOGINUNICO_URLPROVIDER: "${MODULO_LOGINUNICO_URLPROVIDER}"
  MODULO_LOGINUNICO_REDIRECTURL: "${MODULO_LOGINUNICO_REDIRECTURL}"
  MODULO_LOGINUNICO_URLLOGOUT: "${MODULO_LOGINUNICO_URLLOGOUT}"
  MODULO_LOGINUNICO_SCOPE: "${MODULO_LOGINUNICO_SCOPE}"
  MODULO_LOGINUNICO_URLSERVICOS: "${MODULO_LOGINUNICO_URLSERVICOS}"
  MODULO_LOGINUNICO_URLREVALIDACAO: "${MODULO_LOGINUNICO_URLREVALIDACAO}"
  MODULO_LOGINUNICO_CIENTIDVALIDACAO: "${MODULO_LOGINUNICO_CIENTIDVALIDACAO}"
  MODULO_LOGINUNICO_SECRETVALIDACAO: "${MODULO_LOGINUNICO_SECRETVALIDACAO}"
  MODULO_LOGINUNICO_ORGAO: "${MODULO_LOGINUNICO_ORGAO}"
  MODULO_ASSINATURAVANCADA_INSTALAR: "${MODULO_ASSINATURAVANCADA_INSTALAR}"
  MODULO_ASSINATURAVANCADA_VERSAO: "${MODULO_ASSINATURAVANCADA_VERSAO}"
  MODULO_ASSINATURAVANCADA_CLIENTID: "${MODULO_ASSINATURAVANCADA_CLIENTID}"
  MODULO_ASSINATURAVANCADA_SECRET: "${MODULO_ASSINATURAVANCADA_SECRET}"
  MODULO_ASSINATURAVANCADA_URLPROVIDER: "${MODULO_ASSINATURAVANCADA_URLPROVIDER}"
  MODULO_ASSINATURAVANCADA_URL_SERVICOS: "${MODULO_ASSINATURAVANCADA_URL_SERVICOS}"
  MODULO_PEN_INSTALAR: "${MODULO_PEN_INSTALAR}"
  MODULO_PEN_VERSAO: "${MODULO_PEN_VERSAO}"
  MODULO_PEN_WEBSERVICE: "${MODULO_PEN_WEBSERVICE}"
  MODULO_PEN_CERTIFICADO_SENHA: "${MODULO_PEN_CERTIFICADO_SENHA}"
  MODULO_PEN_CERTIFICADO_BASE64: "${MODULO_PEN_CERTIFICADO_BASE64}"
  MODULO_PEN_GEARMAN_IP: "${MODULO_PEN_GEARMAN_IP}"
  MODULO_PEN_GEARMAN_PORTA: "${MODULO_PEN_GEARMAN_PORTA}"
  MODULO_PEN_QTD_WORKER_PROC: "${MODULO_PEN_QTD_WORKER_PROC}"
  MODULO_PEN_REPOSITORIO_ORIGEM: "${MODULO_PEN_REPOSITORIO_ORIGEM}"
  MODULO_PEN_TIPO_PROCESSO_EXTERNO: "${MODULO_PEN_TIPO_PROCESSO_EXTERNO}"
  MODULO_PEN_UNIDADE_GERADORA: "${MODULO_PEN_UNIDADE_GERADORA}"
  MODULO_PEN_UNIDADE_ASSOCIACAO_PEN: "${MODULO_PEN_UNIDADE_ASSOCIACAO_PEN}"
  MODULO_PEN_UNIDADE_ASSOCIACAO_SEI: "${MODULO_PEN_UNIDADE_ASSOCIACAO_SEI}"
  MODULO_PETICIONAMENTO_INSTALAR: "${MODULO_PETICIONAMENTO_INSTALAR}"
  MODULO_PETICIONAMENTO_VERSAO: "${MODULO_PETICIONAMENTO_VERSAO}"
  MODULO_PETICIONAMENTO_URL: "${MODULO_PETICIONAMENTO_URL}"
  MODULO_PI_INSTALAR: "${MODULO_PI_INSTALAR}"
  MODULO_PI_VERSAO: "${MODULO_PI_VERSAO}"
  MODULO_PI_URL: "${MODULO_PI_URL}"
  MODULO_PI_USUARIO: "${MODULO_PI_USUARIO}"
  MODULO_PI_SENHA: "${MODULO_PI_SENHA}"
  MODULO_PI_EMAIL: "${MODULO_PI_EMAIL}"
kind: ConfigMap
metadata:
  name: sei-app
  namespace: "${KUBERNETES_NAMESPACE}"